export const candidConversationsMasterlist: {
  [key: string]: string[];
}[] = [
  {
    "self discovery": [
      "What’s a version of me I secretly miss?",
      "How do I define authenticity in my life?",
      "What do I know about myself now that I didn’t last year?",
      "When do I feel most powerful?",
      "What part of me needs more attention?",
      "How do I handle internal conflict?",
      "What am I afraid people will find out about me?",
      "What makes me feel like I belong in my own body?",
      "Where do I go (mentally or physically) to feel like myself?",
      "What’s one thing I no longer pretend to enjoy?",
      "Who am I when I’m not performing?",
      "What am I still healing from that I don’t always name?",
      "How do I recognize growth in myself?",
      "When have I felt most aligned with my purpose?",
      "What does rest *really* look like for me?",
      "What stories about myself am I still unlearning?",
      "How do I handle being misunderstood?",
      "What patterns keep me from evolving?",
      "What is one question I need to ask myself more often?",
      "What do I want to be known for—honestly?",
      "What does peace feel like in my life right now?",
      "What’s one part of myself I’m learning to embrace?",
      "What does success *really* mean to me?",
      "What do I do when no one is expecting anything from me?",
      "When was the last time I truly surprised myself?",
      "How do I define self-respect?",
      "What brings me back to myself when I feel lost?",
      "What’s a truth I’ve grown into over time?",
      "When do I feel most connected to my intuition?",
      "What am I discovering about myself lately?",
      "How do I stay grounded when life gets chaotic?",
      "What stories have I inherited that I no longer believe?",
      "What helps me feel like I’m evolving?",
      "What emotions do I avoid, and why?",
      "What’s one area of my life where I want more freedom?",
      "What does the phrase 'coming home to myself' mean to me?",
      "What does being present look like for me?",
      "What’s one habit that helps me stay self-aware?",
      "What does it look like to love myself on hard days?",
      "How do I check in with my own needs regularly?",
    ],
  },
  {
    "relationships & connections": [
      "Who makes me feel safe without saying a word?",
      "What’s a love language I give but struggle to receive?",
      "When have I felt most emotionally held?",
      "What does “emotional intimacy” mean to me?",
      "How do I know I’m being truly listened to?",
      "What’s one relationship that taught me the most?",
      "When do I tend to self-abandon in relationships?",
      "What does it mean to show up for someone I love?",
      "What do I need more of in my current connections?",
      "How do I ask for what I need?",
      "Who taught me how to love, and what did they teach me?",
      "What feels like too much to share, even with people I trust?",
      "What does loyalty look like in my life right now?",
      "What role does vulnerability play in my relationships?",
      "How do I know when to let go?",
      "What part of connection do I crave but fear?",
      "What’s a boundary that changed my life?",
      "How do I reconnect with people after conflict or distance?",
      "What do I appreciate most in a friend or partner?",
      "Who has truly *seen* me, and how did it feel?",
      "What does reciprocity feel like in my relationships?",
      "When do I feel most emotionally generous?",
      "What’s one conversation I’ve been avoiding?",
      "Who in my life sees me clearly—and how do they show it?",
      "How do I define emotional labor in relationships?",
      "What’s a relationship I’ve outgrown with love?",
      "How do I show care when I’m not at my best?",
      "When do I feel most connected to others?",
      "What boundaries have made me feel more free?",
      "How do I know when I’m emotionally safe with someone?",
      "What’s one way I want to improve how I show up for others?",
      "What do I need to feel secure in my connections?",
      "What part of intimacy feels hardest for me?",
      "What makes a relationship feel sacred to me?",
      "How do I nurture trust in my relationships?",
      "What does repair look like in my healthiest relationships?",
      "When have I felt seen without needing to explain myself?",
      "What role does community play in my healing?",
      "What makes me feel emotionally fed?",
      "Who do I trust with my truth?",
    ],
  },
  {
    "identity & growth": [
      "How has my identity shifted over time?",
      "Where do I feel like I can show up fully and freely?",
      "What does liberation look like to me?",
      "What’s one identity I’m reclaiming or redefining?",
      "Who am I when no one is watching?",
      "How do my ancestors or lineage influence me?",
      "What does it mean to take up space?",
      "What are the unspoken rules I’ve learned about my identity?",
      "How do I resist shrinking?",
      "What masks do I wear to stay “safe”?",
      "What do I love most about my culture or heritage?",
      "What does “being whole” mean to me?",
      "What systems have shaped how I see myself?",
      "What strengths come from the identities I hold?",
      "Where do I still feel like I’m becoming?",
      "What does being “too much” mean to me?",
      "What’s one way I self-define that others may not understand?",
      "How do I balance personal identity with community?",
      "What does grace look like in my growth process?",
      "What am I still learning to accept about myself?",
      "What parts of my identity do I lead with most often?",
      "How do I navigate being ‘in between’ identities?",
      "What does empowerment mean to me right now?",
      "Where do I feel like I’m still becoming?",
      "What is a cultural value I hold close and why?",
      "How do I respond to external definitions of who I ‘should’ be?",
      "Where in my life do I need more permission to evolve?",
      "What does being grounded in my identity feel like?",
      "What’s something I’ve reclaimed that once brought me shame?",
      "How do I integrate all parts of myself when I’m in public?",
      "What’s one story about myself I’m rewriting?",
      "What have I inherited that I want to pass down?",
      "What makes me feel like I’m living in my purpose?",
      "What does cultural pride look like in my day-to-day life?",
      "What helps me reconnect with my roots?",
      "What’s one internalized belief I’ve released?",
      "Where do I hold both pride and pain in my identity?",
      "What’s one thing I no longer minimize about myself?",
      "What do I want future generations to know about me?",
      "What values guide the way I live my life?",
    ],
  },
  {
    "playful & creative": [
      "What would my drag name or alter ego be?",
      "What’s a silly habit I secretly enjoy?",
      "What’s a hype song that always gets me in my zone?",
      "What’s a fictional character I deeply relate to?",
      "If I had a signature scent, what would it smell like?",
      "What’s my fantasy job in an alternate life?",
      "What’s a personal “ritual” that no one else understands?",
      "If my joy had a texture, what would it feel like?",
      "What’s a movie moment that describes my vibe?",
      "If I threw a themed party for my inner child, what would it be?",
      "What’s my love language in memes?",
      "What animal would represent me right now and why?",
      "What’s my go-to daydream when I want to escape?",
      "If confidence were an outfit, what am I wearing?",
      "What’s a creative idea I’ve had but never shared?",
      "If I could teleport anywhere right now, where would I go?",
      "What’s my inner rebel saying today?",
      "What emoji sums up my week?",
      "If I had a billboard with one message, what would it say?",
      "What’s a small, weird joy I want to protect?",
      "If I created my own holiday, what would we celebrate?",
      "What’s my dream performance or spotlight moment?",
      "If my joy had a playlist, what 3 songs would be on it?",
      "What creative activity makes me lose track of time?",
      "What’s a childhood game or toy I secretly still love?",
      "If I had a personal logo, what would it look like?",
      "What’s a magical object I wish I owned?",
      "If I were a season, which one and why?",
      "What’s a small adventure I’ve been craving?",
      "What food feels like a whole personality?",
      "If I hosted a talk show, what would it be called?",
      "What trend or style would I unapologetically bring back?",
      "What book or movie world would I live in for a day?",
      "If my creativity had a motto, what would it be?",
      "What’s a fantasy version of a regular day I’d love to live?",
      "What’s the quirkiest compliment I’ve ever received?",
      "What imaginary friend or inner character would I revive?",
      "If I wrote a memoir, what would the title be?",
      "What’s a spontaneous idea I’d love to follow through on?",
      "If my life were a board game, what would be the wild card?",
    ],
  },
  {
    "deep cuts & emotional insight": [
      "What’s a truth I’m still scared to say out loud?",
      "Where do I still shrink myself out of fear?",
      "What am I grieving that no one sees?",
      "When do I feel like I’m too much—or not enough?",
      "What’s a pain I’ve turned into power?",
      "Where does my self-doubt live, and what does it sound like?",
      "Who would I be if I weren’t trying to protect myself?",
      "What am I holding that’s not mine to carry?",
      "What does shame whisper to me?",
      "How do I respond when I feel rejected?",
      "What’s something I’m avoiding because I know it will change me?",
      "What do I need to forgive myself for?",
      "When was the last time I felt emotionally raw?",
      "What armor do I wear that once protected me—but no longer serves me?",
      "What’s a lesson I’ve had to learn more than once?",
      "Where in my life do I feel most vulnerable?",
      "What do I need to release to grow?",
      "What’s one emotion I try to avoid at all costs?",
      "What does emotional safety feel like in my body?",
      "How do I know I’m healing, even when it doesn’t feel like it?",
      "What’s a fear that’s shaped how I move through the world?",
      "What does emotional courage mean to me?",
      "When have I silenced myself out of fear of being too much?",
      "Where in my body do I carry my stress or sadness?",
      "What does inner peace feel like for me?",
      "What pain am I still trying to make sense of?",
      "When have I felt emotionally disoriented?",
      "What’s something I’m grieving that’s hard to name?",
      "What helps me feel emotionally safe enough to open up?",
      "What wound have I turned into wisdom?",
      "How do I rebuild trust after it’s been broken?",
      "What do I do when I feel emotionally shut down?",
      "What part of me still believes I have to earn love?",
      "What does it feel like when I’m emotionally full?",
      "When did I first learn to hide my feelings?",
      "What helps me process hard emotions?",
      "What’s one thing I’ve let go of that felt like loss and freedom?",
      "When do I feel closest to my inner strength?",
      "What do I wish someone had told me when I was hurting?",
      "How do I hold space for my own pain without judgment?",
    ],
  },
  {
    "client-inspired & therapeutic": [
      "When was the last time I felt deeply comforted—what helped?",
      "What does my body try to tell me that I don’t always hear?",
      "How do I balance taking care of others with showing up for myself?",
      "What does emotional safety look like in real-time for me?",
      "Where in my life am I surrendering vs. giving up?",
      "What does it mean to show up even when I feel unseen?",
      "How do I know when I’m spiraling—and what helps me out of it?",
      "What’s a coping habit I use that started as survival?",
      "What does my version of being “soft” or “open” look like?",
      "What’s a narrative about myself that I’m rewriting?",
      "What habits protect me but also isolate me?",
      "When do I feel most disconnected from myself?",
      "What are signs I’m nearing burnout?",
      "When did I last listen to my body’s wisdom?",
      "What does my anxiety need from me right now?",
      "What role does guilt play in my daily decisions?",
      "What unmet need shows up the most in my relationships?",
      "How does perfectionism affect how I connect with others?",
      "What boundaries do I need with myself?",
      "What does grace for myself actually look like in practice?",
      "What part of me is still waiting to be acknowledged?",
      "When do I feel safest asking for help?",
      "What survival skills do I still use in moments I no longer need them?",
      "What has my inner child been trying to say lately?",
      "How do I emotionally recover after being triggered?",
      "What does nourishment (not just food) look like for me right now?",
      "Where do I carry shame that’s not mine?",
      "What version of me is trying to emerge?",
      "How does grief show up in my body?",
      "What emotions have I been avoiding and why?",
      "What parts of me feel most unloved—and how can I care for them?",
      "What kind of support do I struggle to receive?",
      "How do I reclaim softness in a world that rewards hardness?",
      "What do I wish I could say to my past self right now?",
      "Where in my life do I still feel like I’m performing?",
      "How do I hold space for both joy and sorrow?",
      "What truths about my healing process have I accepted?",
      "When do I feel most emotionally resilient?",
      "What kind of love am I learning to accept?",
      "What version of safety did I grow up with, and how does it differ now?",
    ],
  },
  {
    "brutally honest & raw": [
      "What lie do I tell myself most often?",
      "When have I been my own worst enemy?",
      "What truth am I avoiding because it hurts too much?",
      "What part of myself do I secretly despise?",
      "When did I settle for less than I deserved—and why?",
      "What toxic pattern do I keep repeating?",
      "Who have I hurt but never apologized to?",
      "When have I acted out of fear instead of love?",
      "What am I scared others will find out about me?",
      "What’s the harshest judgment I’ve placed on myself?",
      "When have I pretended to be someone I’m not?",
      "What uncomfortable feeling do I refuse to sit with?",
      "How do I sabotage my own success?",
      "What do I hate about my past choices?",
      "When do I act small to avoid conflict?",
      "What parts of myself do I hide from the people I love?",
      "When have I prioritized others’ needs over my own to my detriment?",
      "What’s one thing I regret but haven’t faced fully?",
      "When have I been jealous or resentful, and what did I do with those feelings?",
      "What fear keeps me stuck?",
      "How do I handle guilt, and is it helping me?",
      "What does “forgiveness” feel like when I’m honest with myself?",
      "When do I feel the most lonely, even when surrounded by people?",
      "What part of my identity feels like a burden?",
      "How often do I compare myself to others—and how does that affect me?",
      "What’s a secret I’m afraid would change how people see me?",
      "When have I been dishonest with myself?",
      "What’s one uncomfortable truth about my relationships?",
      "How do I cope when I feel emotionally numb?",
      "When do I refuse help, even when I need it?",
      "What’s a boundary I’ve ignored to avoid being seen as “difficult”?",
      "What shame do I carry that I never talk about?",
      "How do I punish myself when I fail?",
      "What do I avoid because it might shatter my self-image?",
      "When have I felt the most disconnected from myself?",
      "What does “being real” mean when no one else is watching?",
      "How do I react when I feel rejected or abandoned?",
      "What’s the hardest apology I’ve had to give or receive?",
      "When do I put on a mask to hide pain?",
      "What truth about myself am I ready to face now?",
    ],
  },
];
